version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: currency-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jj7i55nLD4
      POSTGRES_DB: currency_db
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d currency_db" ]
      interval: 20s
      timeout: 5s
      retries: 3
    restart: always
